### PR TITLE
Fixed some grammar issues and typos

### PR DESCRIPTION
**Pull request by bitdaw**
Found and fixed various typos and grammar issues 🙂

### CODE REVIEW

**Comment by akrabat** [comment]
Why did you close?

**Comment by bitdaw** [comment]
I was clearing out some of my forks and I didn't realise this one still had an open PR  😬 🙁

**Comment by bitdaw** [comment]
I can create a new one

**Comment by akrabat** [comment]
Ah! It's up to you :) I'm happy to recreate, but if you do it, you get the credit.

**Comment by bitdaw** [comment]
I'm on it now, give me 5 and the new PR will be there :)

**Pull request closed without merging**
