### PR TITLE
First slim app tutorial

### PR DESCRIPTION
**Pull request by lornajane**
Here is a detailed tutorial for creating a first Slim Framework 3 application, I thought you might like to have it in your docs.

Things to note:
- it's quite long
- there is sample code that's currently on a bitbucket repo but I'm happy to put that somewhere you can accept changes to it

### CODE REVIEW

**Comment by lornajane** [comment]
I've pushed the example code to the new repo that was created and updated the tutorial to link to it

**Comment by chroda** [comment]
Why the codes github page is not referenced in the website?

If is, please show me exactly location of url reference.

Thanks ;)

**Comment by akrabat** [comment]
On [https://www.slimframework.com/docs/tutorial/first-app.html](https://www.slimframework.com/docs/tutorial/first-app.html), you can see this:

screen shot 2017-04-04 at 15 02 53

**Comment by chroda** [comment]
Guess I need change my glasses hahha, thanks a lot @akrabat

**Pull request merged**
