### PR TITLE
gh-195 added example slim application to handle file uploads

### PR DESCRIPTION
**Pull request by llvdl**
also added link to post by Rob Allen

### CODE REVIEW

**Comment by akrabat** [comment]
Great work. Thanks.

**Comment by danielMensah** [comment]
@llvdl nice one. However I get an error with the `$uploadedFile->getError()` 
` Uncaught Error: Call to a member function getError() on null`

**Comment by llvdl** [comment]
Hello @danielMensah,

Thanks for reaching out. I can't reproduce the error you mentioned. I have ran the example code, submitting the form both with and without attachments. 

Can you add a link to a minimal example where you are seeing this error and the steps you take that lead to the error?

**Comment by dongido001** [comment]
Hi @danielgsims 

Although this is an old thread. Just want to put it here for users that might hit the same errors.

You should make sure you are setting this encoding type in your form:

```html
<form enctype="multipart/form-data">
```

**Pull request merged**
