### PR TITLE
add Atlas entry to the cookbook navigation

### PR DESCRIPTION
**Pull request by pmjones**

### CODE REVIEW

**Comment by svpernova09** [comment]
My OCD thinks they should be in alphabetical order. (Atlas -> Doctrine -> Eloquent).

Thoughts @silentworks, @akrabat ?

**Comment by pmjones** [comment]
My first edit was to put them in alpha order but I did not want to look like I was self-dealing.

**Comment by akrabat** [comment]
I have no particular views either way. I can see a strong argument for alphabetical ordering for the entire Cook book section and can also see an argument for grouping based on "related topic". 

i.e. Whatever you think works best @svpernova09.

**Comment by svpernova09** [comment]
> My first edit was to put them in alpha order but I did not want to look like I was self-dealing.

Fair

>i.e. Whatever you think works best @svpernova09.

We'll roll with this as is, and we can reorder later. Thanks @akrabat @pmjones !

**Pull request merged**
