### PR TITLE
Removed documentation on getIp() [method removed for security reasons]

### PR DESCRIPTION
**Pull request by AndrewCarterUK**
see: https://github.com/slimphp/Slim/pull/1559

### CODE REVIEW

**Comment by akrabat** [comment]
Ideally, we also need to document how to use middleware to perform this feature. 

Presumably some sort of cookbook type page?

**Comment by silentworks** [comment]
Yeah a cookbook type page makes sense.

**Comment by AndrewCarterUK** [comment]
That would be helpful

**Comment by akrabat** [comment]
Cookbook section now available - just need an article added…

**Comment by akrabat** [comment]
The section has been removed in another patch, so all done.

Cookbook entry also created now: http://www.slimframework.com/docs/cookbook/ip-address.html

**Pull request closed without merging**
