### PR TITLE
gh-263 consistently use $args instead of $request->getAttribute for route placehol…

### PR DESCRIPTION
**Pull request by llvdl**
…der values

### CODE REVIEW

**Comment by llvdl** [comment]
See issue #263

**Review by Rotzbua — APPROVED** [review]

**Comment by akrabat** [comment]
Needs a rebase. Though, it's probably easier to just create a new PR.

**Comment by llvdl** [comment]
I rebased the PR.

**Comment by akrabat** [comment]
Ta.

**Pull request merged**
