### PR TITLE
[WIP] Translation to Brazilian Portuguese (pt-br)

### PR DESCRIPTION
**Pull request by mathmarques**
### PT-BR version of Slim's User Guide
This is a **W**ork **I**n **P**rogress and any help is wanted
Discussion started on https://github.com/slimphp/Slim-Website/issues/248

### Wanna help? 
- Fork & Clone [this repo](https://github.com/mathmarques/Slim-Website/tree/brazilian-portuguese )
- Follow the [README](https://github.com/slimphp/Slim-Website/blob/gh-pages/README.md) and run the Slim Website locally.
- To access the translated user guide use the link: http://localhost:4000/docs/pt-br/ 
- Select a file from the TO-DO List bellow to translate
- PR the translation against [mathmarques/Slim-Website/tree/brazilian-portuguese](https://github.com/mathmarques/Slim-Website/tree/brazilian-portuguese )

### General
- [x] Add pt-br sections on _config.yml 
- [ ] Fix searchbox for the pt-br doc
- [ ] Add a language selector 
### Translation
- [ ] docs/pt-br//index.md  **(being translated by @mathmarques )**
- [x] docs/pt-br/concepts/di.md (translated by @jmrodriguesgoncalves)**(needs revision)**
- [x] docs/pt-br/concepts/life-cycle.md (translated by @jmrodriguesgoncalves)**(needs revision)**
- [x] docs/pt-br/concepts/middleware.md (translated by @jmrodriguesgoncalves)**(needs revision)**
- [x] docs/pt-br/concepts/value-objects.md (translated by @jmrodriguesgoncalves)**(needs revision)**
- [x] docs/pt-br/contributors/guidelines.md (translated by @jmrodriguesgoncalves)**(needs revision)**
- [x] docs/pt-br/contributors/strategy.md (translated by @jmrodriguesgoncalves)**(needs revision)**
- [x] docs/pt-br/cookbook/action-domain-responder.md (translated by @jmrodriguesgoncalves)**(needs revision)**
- [x] docs/pt-br/cookbook/database-eloquent.md (translated by @jmrodriguesgoncalves)**(needs revision)**
- [x] docs/pt-br/cookbook/enable-cors.md (translated by @jmrodriguesgoncalves)**(needs revision)**
- [x] docs/pt-br/cookbook/environment.md (translated by @jmrodriguesgoncalves)**(needs revision)**
- [x] docs/pt-br/cookbook/ip-address.md (translated by @jmrodriguesgoncalves)**(needs revision)**
- [x] docs/pt-br/cookbook/retrieving-current-route.md (translated by @jmrodriguesgoncalves)**(needs revision)**
- [x] docs/pt-br/cookbook/route-patterns.md (translated by @jmrodriguesgoncalves)**(needs revision)**
- [x] docs/pt-br/cookbook/uploading-files.md (translated by @jmrodriguesgoncalves)**(needs revision)**
- [x] docs/pt-br/deployment/deployment.md (translated by @jmrodriguesgoncalves)**(needs revision)**
- [x] docs/pt-br/features/caching.md (translated by @jmrodriguesgoncalves)**(needs revision)**
- [x] docs/pt-br/features/csrf.md (translated by @jmrodriguesgoncalves)**(needs revision)**
- [x] docs/pt-br/features/flash.md (translated by @jmrodriguesgoncalves)**(needs revision)**
- [x] docs/pt-br/features/templates.md (translated by @jmrodriguesgoncalves)**(needs revision)**
- [x] docs/pt-br/handlers/error.md (translated by @jmrodriguesgoncalves)**(needs revision)**
- [x] docs/pt-br/handlers/not-allowed.md (translated by @jmrodriguesgoncalves)**(needs revision)**
- [x] docs/pt-br/handlers/not-found.md (translated by @jmrodriguesgoncalves)**(needs revision)**
- [x] docs/pt-br/handlers/php-error.md (translated by @jmrodriguesgoncalves)**(needs revision)**
- [x] docs/pt-br/objects/application.md (translated by @jmrodriguesgoncalves)**(needs revision)**
- [x] docs/pt-br/objects/request.md (translated by @jmrodriguesgoncalves)**(needs revision)**
- [x] docs/pt-br/objects/response.md (translated by @jmrodriguesgoncalves)**(needs revision)**
- [x] docs/pt-br/objects/router.md (translated by @jmrodriguesgoncalves)**(needs revision)**
- [x] docs/pt-br/start/installation.md (translated by @jmrodriguesgoncalves)**(needs revision)**
- [x] docs/pt-br/start/upgrade.md (translated by @jmrodriguesgoncalves)**(needs revision)**
- [x] docs/pt-br/start/web-servers.md (translated by @jmrodriguesgoncalves)**(needs revision)**
- [x] docs/pt-br/tutorial/first-app.md (translated by @jmrodriguesgoncalves)**(needs revision)**

## Disclaimer
This branch is sync with the commit https://github.com/slimphp/Slim-Website/commit/d75a928f26543760855c3f0777d27a0592c97829 from Dec 20, 2017

### CODE REVIEW

**Comment by jmrodriguesgoncalves** [comment]
I could try and help out with some of these, I am currently studying software development and I am pitching into different projects to get more Open Source experience. I am not Brazilian, I am Portuguese (from Portugal). The two languages are very, very similar (like British to American English) but there are some differences. So I could help by either:

a) giving you a PT-PT translation
or...
b) giving you a PT-BR translation, in which I would use a bit of software help, in order for it all to be 100% accurate Brazilian Portuguese.

Lemme know if I can help!

**Comment by mathmarques** [comment]
Hello @jmrodriguesgoncalve I would love the help!
You can PR me the PT-PT version and I check it out!

**Comment by marcuxyz** [comment]
@mathmarques do you going to fix the trouble?

**Comment by l0gicgate** [comment]
Is there going to be any new progress with this? Otherwise I will close this PR as it is stale.

**Comment by l0gicgate** [comment]
Feel free to re-open with new localization structure.

**Pull request closed without merging**
