### PR TITLE
Grammer correction

### PR DESCRIPTION
**Pull request by Reaper45**
Its grammatically incorrect to say ...an HTTP request.

### CODE REVIEW

**Comment by tkovs** [comment]
Did you fix all occurrences in this branch?

**Comment by Reaper45** [comment]
Not exactly.  Only fixed occurrences in the home page.

**Comment by tkovs** [comment]
Using sublime text (example), you can find all occurrences of this. I'll check here

**Comment by tkovs** [comment]
```Slim-Website\_posts\2011-09-15-slim-application-lifecycle.md:```
    5  ---
    6  
    7: The essence of a web application is simple: it receives **HERE** an HTTP **HERE** request; it invokes the appropriate code; and it returns **HERE** an HTTP **HERE** response. The Slim Framework makes it dead simple to build and launch small web applications and APIs by hiding the prerequisite application underpinnings beneath a simple, easy-to-use interface. But for those interested in the low-level details, here’s what a Slim application’s lifecycle looks like from start to finish.
    8  
    9  ## Instantiation
   ..
   26  {% endhighlight %}
   27  
   28: This example demonstrates a Route mapping the URI “/foo” to specific controller code for **HERE** an HTTP **HERE** GET request. The `$app->get()`, `$app->post()`, `$app->put()`, `$app->delete()`, `$app->options()`, or `$app->map()` Slim application instance methods may be used to define application routes that respond to the respective HTTP request methods.
   29  
   30  When one of these Slim application instance methods is invoked to define a Route, the Router object relates the given URI to the particular controller code for the given HTTP request method(s) in the form of a Route object.

```Slim-Website\_posts\2011-12-31-automatically-parse-request-by-content-type.md:```
    1  ---
    2: title: Automatically parse **HERE** an HTTP **HERE** request by content type
    3: description: Learn how to automatically parse **HERE** an HTTP **HERE** request body using Slim Framework middleware
    4  layout: post
    5  ---
    .
   16  ## JSON Requests
   17  
   18: This middleware will parse a JSON request’s body into an associative array. Imagine you send **HERE** an HTTP **HERE** request to the POST route below. The request body is `{"name":"John","email":"john.doe@gmail.com"}`.
   19  
   20  {% highlight php %}
   ..
   28  ## XML Requests
   29  
   30: This middleware will parse a XML request’s body into a SimpleXMLElement instance if the SimpleXML extension is available; otherwise the body will remain a string. Imagine you send **HERE** an HTTP **HERE** request to the POST route above. The HTTP request body is:
   31  
   32  {% highlight xml %}
   ..
   42  ## CSV Requests
   43  
   44: This middleware will parse a CSV request’s body into an array or arrays. Imagine you send **HERE** an HTTP **HERE** request to the POST route above. The HTTP request body is:
   45  
   46  {% highlight text %}
   ..
   60  ## Custom Content Types
   61  
   62: If you want to parse **HERE** an HTTP **HERE** request body that is not JSON, XML, or CSV you can provide your own parsing functions to this middleware using its optional second argument. You’ll need to know the content type of the incoming HTTP request, and you’ll need to prepare a callable item to parse the request body. The callable item that will parse the HTTP request body should accept a string argument and return the appropriate PHP data structure.
   63  
   64: Imagine we want the POST route above to accept **HERE** an HTTP **HERE** request with an HTML body. We tell our Slim_Middleware_ContentTypes middleware to parse these requests like this:
   65  
   66  {% highlight php %}

```Slim-Website\_posts\2012-04-14-version-160.md:```
   37  Unlike previous versions, Slim Framework 1.6.0 will not start a native PHP session on its own. If you need a native PHP session, you should configure and start a native PHP session on your own before instantiating a Slim application. Many application developers found Slim’s earlier session implementation too presumptuous; the new implementation in 1.6.0 allows more configuration with less assumptions.
   38  
   39: The Slim_Middleware_SessionCookie middleware may be used to persist signed, encrypted session data to **HERE** an HTTP **HERE** cookie just like earlier versions of the Slim Framework.
   40  
   41  [Read More](http://www.slimframework.com/documentation/stable#sessions)

```Slim-Website\docs\index.md:```
   21  Slim is a PHP micro framework that helps you
   22  quickly write simple yet powerful web applications and APIs. At its core, Slim
   23: is a dispatcher that receives **HERE** an HTTP **HERE** request, invokes an appropriate callback
   24: routine, and returns **HERE** an HTTP **HERE** response. That's it.
   25  
   26  ## What's the point?
   ..
   33  
   34  > At its core, Slim
   35: is a dispatcher that receives **HERE** an HTTP **HERE** request, invokes an appropriate callback
   36: routine, and returns **HERE** an HTTP **HERE** response. That's it.
   37  
   38  You don't always need a kitchen-sink solution like [Symfony][symfony] or [Laravel][laravel].
   ..
   48  
   49  A Slim app contains routes that respond to specific HTTP requests. Each route
   50: invokes a callback and returns **HERE** an HTTP **HERE** response. To get started, you first
   51  instantiate and configure the Slim application. Next, you define your application
   52  routes. Finally, you run the Slim application. It's that easy. Here's an

```Slim-Website\docs\objects\response.md:```
  204  ## The Response Body
  205  
  206: **HERE** An HTTP **HERE** response typically has a body. Slim provides a PSR 7 Response object
  207  with which you can inspect and manipulate the eventual HTTP response's body.
  208  

17 matches across 5 files

**Comment by tkovs** [comment]
The occurrences are between **HERE**s

**Comment by Reaper45** [comment]
Okay. I'll go through it and update.

**Comment by Amgine0** [comment]
Note: standard pronunciation is /eɪtʃ-tiː-tiː-piː/, not /htʰtʰp/. This is an initialism, not a pronounced acronym.

**Comment by Reaper45** [comment]
You are correct @Amgine0 . This is the same as hour, honour,  etc. Am gonna close this now. Thanks for pointing out. Cheers.

**Pull request closed without merging**
