### PR TITLE
Update Doctrine Cookbook to v3.0

### PR DESCRIPTION
**Pull request by 1ma**
Upgrades the guide to the latest major version of `doctrine/orm`, released last February.

The referenced sample repository has also been upgraded.

### CODE REVIEW

**Comment by carlosmintfan** [comment]
Should be merged ASAP. I was having trouble with finding the console path until I discovered the change on doctrine docs and GitHub and then I looked if there was already a PR for pointing the change out here (would create an issue otherwise) and found it. Thanks!

**Comment by carlosmintfan** [comment]
Btw, shouldn't we use php-di instead of Uma\Dic here? PHP-Di seems the standard in slim, so this could be a bit confusing.

**Comment by carlosmintfan** [comment]
Well, er, are you yourself the developer of UMA, @1ma ? Hmm. 🤔 😄 Well, we should define a standard in Slim, I think…and PHP-Di has been the standard.

**Comment by 1ma** [comment]
Yes, though I'll point out that there is no standard anything in Slim. It's a minimalistic Bring-Your-Own-Component framework.

Regarding Dependency Injection the only point of contact with the framework is the `ContainerInterface` from `psr/container`.

**Review by akrabat — APPROVED** [review]

**Comment by akrabat** [comment]
DIC is a user-choice, so I'm happy to see different DICs used in cookbooks. 

If we ever standardised on a DIC, then maybe we'd change this, but it's good to show that it's swappable.

**Pull request merged**
