### PR TITLE
Update web-servers.md

### PR DESCRIPTION
**Pull request by guizoxxv**
Only apply rewrite rules if Apache mod_rewrite module is active.

### CODE REVIEW

**Comment by geggleto** [comment]
Slim requires the mod_rewrite so I don't see a point to guarding against it not being enabled.

**Comment by guizoxxv** [comment]
My Slim application was using the .htaccess code from this page and I was getting a 500 Internal Server Error. Took me almost a day until I realize that mod_rewrite was required and I only got into this conclusion after I saw the `<IfModule mod_rewrite.c>` on [Slim's official Slim-Skeleton base .htaccess](https://github.com/slimphp/Slim-Skeleton/blob/master/public/.htaccess). Why is it there and not in Slim's Apache configuration documentation?
I still think the .htaccess should include `<IfModule mod_rewrite.c>` instead of assuming that mod_rewrite is enabled.

**Comment by geggleto** [comment]
At least from my point-of-view the fact that it 500'd should have lead you to check the log files and see that there was a server misconfiguration. If we add the mod_rewrite check then it will silently fail which will likely lead to more support requests.

The Slim-Skeleton's htaccess I am unfamiliar with as htaccess provided in Slim/Slim is quite different and is actually the code that is on the website.

//cc @akrabat

**Comment by guizoxxv** [comment]
The 500 Internal Server Error page does say "More information about this error may be available in the server error log.".  I did understand what you said about silently fail but when I checked Apache error log in /var/log/apache2/error.log it was empty and PHP display_errors=On. Perhaps I`m not configuring Apache correctly.
Slim's installation page documentation does include "Web server with URL rewriting" on System Requirements but I believe it should also be mentioned on Apache (or others) configuration documentation. I've updated the file changes keeping the .htaccess code but mentioning Apache mod_rewrite.

**Comment by akrabat** [comment]
Thanks @guizoxxv! Calling out that mod_rewrite is needed is a good idea.

**Pull request merged**
