### PR TITLE
Added Slim API reference

### PR DESCRIPTION
**Pull request by ghost**
As I said in https://github.com/slimphp/Slim-Website/issues/213 this is the Slim API reference.
It's generated from latest version of Slim 3.x using https://github.com/FriendsOfPHP/sami

### CODE REVIEW

**Comment by sjzurek** [comment]
That was quick!
Well done! I think the community will much appreciate it.

+1 from me!

**Comment by akrabat** [comment]
This needs to be automated as a script so that we can run it for every release.

**Comment by ghost** [comment]
@akrabat I thought the same, let me know how I can help with this

**Comment by rechl** [comment]
This could be done with travis on each commit. 
Similar as described here
 https://github.com/ApiGen/ApiGen/wiki/Generate-API-to-Github-pages-via-Travis 

But gh-pages branch must be added to slimphp/slim 
And I could not figure out how to execute this only on a new release and not on every commit.

**Pull request closed without merging**
