### PR TITLE
added indication for current section in docs navigation

### PR DESCRIPTION
**Pull request by llvdl**
See http://discourse.slimframework.com/t/suggestion-for-slim-official-documentation/439

### CODE REVIEW

**Comment by akrabat** [comment]
Hi,

I really like this idea. Can we also highlight the actual page too?

e.g. https://i.19ft.com/a3486071.png should highlight "Dependency Container" under the "Concepts" section. Maybe by making it bold or a different colour?

**Comment by llvdl** [comment]
Hello @akrabat , 

I tried to highlight the actual page, but I wasn't able to reliably do so using the Jekyll templates. 

Certain pages contain multiple sections and have multiple menu items that point to the same page with an anchor, e.g. http://www.slimframework.com/docs/objects/request.html#the-request-headers. Because the pages are rendered beforehand using Jekyll and not during the page request, the URL fragment is not available.

Can I split the current pages with multiple sections into separate pages? That way each menu item corresponds to a single page.

If that isn't desirable I can also add some javascript code to determine the actual page in the current page structure instead.

**Comment by akrabat** [comment]
You most definitely can reorganise the files so that the menu highlight works!

**Comment by llvdl** [comment]
I have been thinking about this some more. Changing the page structure might render links to specific documentation pages invalid. I have added a  javascript solution instead.

**Comment by akrabat** [comment]
Yeah - that works well. Thank you.

**Pull request merged**
