### PR TITLE
Update docs for array-notation routes

### PR DESCRIPTION
**Pull request by ddrv**
Update docs for https://github.com/slimphp/Slim/pull/3069

### CODE REVIEW

**Comment by odan** [comment]
Hi @ddrv 

I'm not sure if this is really officially supported by Slim.

When I try this:

```php
$app->get('/', [\App\Action\Home\HomeAction::class, '__invoke']);
```

I get this error message because `is_callable` return false:

```
App\Action\Home\HomeAction, __invoke is not resolvable in
 vendor\slim\slim\Slim\CallableResolver.php on line 165
```

This is because `is_callable` requires an object instead.

Demo: https://3v4l.org/vUN3m

https://www.php.net/manual/en/function.is-callable.php

Edit: I just saw your other PR a little to late.

**Comment by ddrv** [comment]
@odan Hi!

I send this Pull Request to update the docs after merging the [Pull Request to framework code ](https://github.com/slimphp/Slim/pull/3069). I should have said this in the description, sorry

**Comment by l0gicgate** [comment]
@odan this feature will be upcoming in 4.8 see https://github.com/slimphp/Slim/pull/3069

**Comment by odan** [comment]
@l0gicgate Yes, I just noticed that after I wrote my comment 😄

**Pull request merged**
