### PR TITLE
Updated middleware documentation

### PR DESCRIPTION
**Pull request by Lewiscowles1986**
- Added middleware group documentation and code examples.
- Added sample `AbstractMiddlewareInvokable` helper class, and code to show usage.
- Added sample code / pro-forma for adding invokable middleware

### CODE REVIEW

**Comment by silentworks** [comment]
Thanks for this PR @Lewiscowles1986 but I think it might be better to just explain before and after than introduce a helper class as this will be helpful for the user to know when dealing with any other PSR7 middleware implementation.

**Comment by Lewiscowles1986** [comment]
Hi @silentworks, message received :+1: and I am happy to change it. The thing is; it is explained it in the docs at that point already without the abstract class, and given an example of before and after, and the code works for any PSR7 middleware implementation still; but for an invokable class, it seems cleaner and more purposeful to declare the before and after implementation, as separate methods. If nothing else, it's there to add to readability, and discourage an úber function inside a class, and unless there is something I am missing, that seems like an awesome thing?

**Removed `AbstractMiddlewareInvokable`**

**Comment by Lewiscowles1986** [comment]
The changes have been made to remove the helper class from the docs, the related issue has been closed... Is anything happening with this?

**Comment by silentworks** [comment]
Will merge soon, I/you will need to make some changes first because of #29

**Comment by Lewiscowles1986** [comment]
so just chaining `getBody()`, done ;)

**Comment by Lewiscowles1986** [comment]
okay this has got messy, new Pull @ https://github.com/slimphp/Slim-Website/pull/33

**Pull request closed without merging**
