### PR TITLE
Update Syntax Highlighter

### PR DESCRIPTION
**Pull request by julionc**
Fixes PHP Syntax Highlighter

### CODE REVIEW

**Comment by julionc** [comment]
Really? A lot of pull requests just to fixes syntax highlighter. :facepunch:
cc: @silentworks

**Comment by silentworks** [comment]
Thanks for the PR.

To address your other point, we will accept multiple PRs as we do not know the person sending in the PR circumstances. For instance they could be doing it a day at a time or during their lunch break or while tending someone else, we are just happy that there are people like yourself willing to take some of their valuable time to help out on the project.

Thanks again to you and @Lewiscowles1986 for sending in PRs to help out.

**Comment by Lewiscowles1986** [comment]
thx I do want to combine when I am not making the edits on an ipad and iphone, but I appreciate the feedback and will try to use this week to make some more site edits. The other reason for single commits (other than my iFruits having to use web client) is reversibility :smile: :+1: @silentworks :+1: @julionc

**Comment by Lewiscowles1986** [comment]
oh and :facepunch: (fistbump) to you too @julionc :laughing:

**Comment by julionc** [comment]
LOL. :stuck_out_tongue_winking_eye: Keep rocking'' Slim Team

**Pull request merged**
